import type { Language } from "./bibleData";

const norwegianBookNames: Record<string, string> = {
  Genesis: "1 Mosebok",
  Exodus: "2 Mosebok",
  Leviticus: "3 Mosebok",
  Numbers: "4 Mosebok",
  Deuteronomy: "5 Mosebok",
  Joshua: "Josva",
  Judges: "Dommerne",
  Ruth: "Rut",
  "1 Samuel": "1 Samuel",
  "2 Samuel": "2 Samuel",
  "1 Kings": "1 Kongebok",
  "2 Kings": "2 Kongebok",
  "1 Chronicles": "1 Kronikebok",
  "2 Chronicles": "2 Kronikebok",
  Ezra: "Esra",
  Nehemiah: "Nehemja",
  Esther: "Ester",
  Job: "Job",
  Psalms: "Salmene",
  Proverbs: "Ordsprakene",
  Ecclesiastes: "Forkynneren",
  "Song of Solomon": "Hoysangen",
  Isaiah: "Jesaja",
  Jeremiah: "Jeremia",
  Lamentations: "Klagesangene",
  Ezekiel: "Esekiel",
  Daniel: "Daniel",
  Hosea: "Hosea",
  Joel: "Joel",
  Amos: "Amos",
  Obadiah: "Obadja",
  Jonah: "Jona",
  Micah: "Mika",
  Nahum: "Nahum",
  Habakkuk: "Habakkuk",
  Zephaniah: "Sefanja",
  Haggai: "Haggai",
  Zechariah: "Sakarja",
  Malachi: "Malaki",
  Matthew: "Matteus",
  Mark: "Markus",
  Luke: "Lukas",
  John: "Johannes",
  Acts: "Apostlenes gjerninger",
  Romans: "Romerne",
  "1 Corinthians": "1 Korinterbrev",
  "2 Corinthians": "2 Korinterbrev",
  Galatians: "Galaterne",
  Ephesians: "Efeserne",
  Philippians: "Filipperne",
  Colossians: "Kolosserne",
  "1 Thessalonians": "1 Tessalonikerbrev",
  "2 Thessalonians": "2 Tessalonikerbrev",
  "1 Timothy": "1 Timoteusbrev",
  "2 Timothy": "2 Timoteusbrev",
  Titus: "Titus",
  Philemon: "Filemon",
  Hebrews: "Hebreerne",
  James: "Jakobs brev",
  "1 Peter": "1 Petersbrev",
  "2 Peter": "2 Petersbrev",
  "1 John": "1 Johannesbrev",
  "2 John": "2 Johannesbrev",
  "3 John": "3 Johannesbrev",
  Jude: "Judas brev",
  Revelation: "Johannes apenbaring",
};

const tigrinyaBookNames: Record<string, string> = {
  Genesis: "ዘፍጥረት",
  Exodus: "ዘጸአት",
  Leviticus: "ዘሌዋውያን",
  Numbers: "ዘህልቍ",
  Deuteronomy: "ዘዳግም",
  Joshua: "እያሱ",
  Judges: "መሳፍንቲ",
  Ruth: "ሩት",
  "1 Samuel": "1ይ ሳሙኤል",
  "2 Samuel": "2ይ ሳሙኤል",
  "1 Kings": "1ይ ነገስት",
  "2 Kings": "2ይ ነገስት",
  "1 Chronicles": "1ይ ዜና መዋእል",
  "2 Chronicles": "2ይ ዜና መዋእል",
  Ezra: "እዝራ",
  Nehemiah: "ነህምያ",
  Esther: "ኣስቴር",
  Job: "እዮብ",
  Psalms: "ዝሙር ዳዊት",
  Proverbs: "ምሳሌ",
  Ecclesiastes: "መክብብ",
  "Song of Solomon": "መኃልየ መኃልይ",
  Isaiah: "ኢሳይያስ",
  Jeremiah: "ኤርምያስ",
  Lamentations: "ድጒዓ ኤርምያስ",
  Ezekiel: "ህዝቅኤል",
  Daniel: "ዳንኤል",
  Hosea: "ሆሴእ",
  Joel: "ዮኤል",
  Amos: "ኣሞጽ",
  Obadiah: "ኣብድዩ",
  Jonah: "ዮናስ",
  Micah: "ሚክያስ",
  Nahum: "ናሆም",
  Habakkuk: "ኣምባቆም",
  Zephaniah: "ጸፎንያስ",
  Haggai: "ሃጌ",
  Zechariah: "ዘካርያስ",
  Malachi: "ሚልክያስ",
  Matthew: "ማቴዎስ",
  Mark: "ማርቆስ",
  Luke: "ሉቃስ",
  John: "ዮሃንስ",
  Acts: "ግብሪ ሃዋርያት",
  Romans: "ሮሜ",
  "1 Corinthians": "1ይ ቆሮንቶስ",
  "2 Corinthians": "2ይ ቆሮንቶስ",
  Galatians: "ገላትያ",
  Ephesians: "ኤፌሶን",
  Philippians: "ፊልጲ",
  Colossians: "ቆሎሴ",
  "1 Thessalonians": "1ይ ተሰሎንቄ",
  "2 Thessalonians": "2ይ ተሰሎንቄ",
  "1 Timothy": "1ይ ጢሞቴዎስ",
  "2 Timothy": "2ይ ጢሞቴዎስ",
  Titus: "ቲቶስ",
  Philemon: "ፊልሞን",
  Hebrews: "እብራውያን",
  James: "ያእቆብ",
  "1 Peter": "1ይ ጴጥሮስ",
  "2 Peter": "2ይ ጴጥሮስ",
  "1 John": "1ይ ዮሃንስ",
  "2 John": "2ይ ዮሃንስ",
  "3 John": "3ይ ዮሃንስ",
  Jude: "ይሁዳ",
  Revelation: "ራእይ ዮሃንስ",
};

const amharicBookNames: Record<string, string> = {
  Genesis: "ዘፍጥረት",
  Exodus: "ዘፀአት",
  Leviticus: "ዘሌዋውያን",
  Numbers: "ዘኍልቍ",
  Deuteronomy: "ዘዳግም",
  Joshua: "ኢያሱ",
  Judges: "መሳፍንት",
  Ruth: "ሩት",
  "1 Samuel": "1 ሳሙኤል",
  "2 Samuel": "2 ሳሙኤል",
  "1 Kings": "1 ነገሥት",
  "2 Kings": "2 ነገሥት",
  "1 Chronicles": "1 ዜና መዋዕል",
  "2 Chronicles": "2 ዜና መዋዕል",
  Ezra: "ዕዝራ",
  Nehemiah: "ነህምያ",
  Esther: "አስቴር",
  Job: "ኢዮብ",
  Psalms: "መዝሙር",
  Proverbs: "ምሳሌ",
  Ecclesiastes: "መክብብ",
  "Song of Solomon": "መኃልየ መኃልይ",
  Isaiah: "ኢሳይያስ",
  Jeremiah: "ኤርምያስ",
  Lamentations: "ሰቆቃወ ኤርምያስ",
  Ezekiel: "ሕዝቅኤል",
  Daniel: "ዳንኤል",
  Hosea: "ሆሴዕ",
  Joel: "ኢዮኤል",
  Amos: "አሞጽ",
  Obadiah: "አብድዩ",
  Jonah: "ዮናስ",
  Micah: "ሚክያስ",
  Nahum: "ናሆም",
  Habakkuk: "ዕንባቆም",
  Zephaniah: "ሶፎንያስ",
  Haggai: "ሐጌ",
  Zechariah: "ዘካርያስ",
  Malachi: "ሚልክያስ",
  Matthew: "ማቴዎስ",
  Mark: "ማርቆስ",
  Luke: "ሉቃስ",
  John: "ዮሐንስ",
  Acts: "የሐዋርያት ሥራ",
  Romans: "ሮሜ",
  "1 Corinthians": "1 ቆሮንቶስ",
  "2 Corinthians": "2 ቆሮንቶስ",
  Galatians: "ገላትያ",
  Ephesians: "ኤፌሶን",
  Philippians: "ፊልጵስዩስ",
  Colossians: "ቆላስይስ",
  "1 Thessalonians": "1 ተሰሎንቄ",
  "2 Thessalonians": "2 ተሰሎንቄ",
  "1 Timothy": "1 ጢሞቴዎስ",
  "2 Timothy": "2 ጢሞቴዎስ",
  Titus: "ቲቶ",
  Philemon: "ፊልሞና",
  Hebrews: "ዕብራውያን",
  James: "ያዕቆብ",
  "1 Peter": "1 ጴጥሮስ",
  "2 Peter": "2 ጴጥሮስ",
  "1 John": "1 ዮሐንስ",
  "2 John": "2 ዮሐንስ",
  "3 John": "3 ዮሐንስ",
  Jude: "ይሁዳ",
  Revelation: "ራእይ",
};

export function getLocalizedBookName(bookName: string, language: Language): string {
  if (language === "no") {
    return norwegianBookNames[bookName] ?? bookName;
  }

  if (language === "ti") {
    return tigrinyaBookNames[bookName] ?? bookName;
  }

  if (language === "am") {
    return amharicBookNames[bookName] ?? bookName;
  }

  return bookName;
}

